import { randomUUID, createHash } from "node:crypto"
import type { ModerationResult } from "./imageModeration/types"

const KEY = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.webp$/
export function isImageKey(key: string) { return key.length === 41 && KEY.test(key) }
/** Only references generated by this application can identify deletable objects.
 * Legacy data URLs, external URLs and malformed paths are deliberately ignored. */
export function storedImageKey(reference: unknown): string | null {
  if (typeof reference !== "string" || !reference.startsWith("/api/media/")) return null
  const key = reference.slice("/api/media/".length)
  return isImageKey(key) ? key : null
}

export async function deleteStoredImage(reference: unknown): Promise<void> {
  const key = storedImageKey(reference)
  if (!key) return
  const { bucket } = imageStorageConfig()
  await storageRequest(`object/${bucket}`, {
    method: "DELETE", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prefixes: [key] }),
  })
}

export function imageStorageConfig() {
  const { IMAGE_STORAGE_URL, IMAGE_STORAGE_KEY, IMAGE_STORAGE_BUCKET } = process.env
  if (!IMAGE_STORAGE_URL || !IMAGE_STORAGE_KEY || !IMAGE_STORAGE_BUCKET) throw new Error("Image storage configuration required")
  let url: URL
  try { url = new URL(IMAGE_STORAGE_URL) } catch { throw new Error("Invalid IMAGE_STORAGE_URL") }
  if (url.protocol !== "https:" || url.username || url.password || url.pathname !== "/" || url.search || url.hash) throw new Error("Invalid IMAGE_STORAGE_URL")
  if (!/^[a-z0-9][a-z0-9-]{0,62}$/.test(IMAGE_STORAGE_BUCKET)) throw new Error("Invalid IMAGE_STORAGE_BUCKET")
  return { origin: url.origin, key: IMAGE_STORAGE_KEY, bucket: IMAGE_STORAGE_BUCKET }
}
async function storageRequest(path: string, init: RequestInit = {}) {
  const config = imageStorageConfig()
  try {
    const response = await fetch(`${config.origin}/storage/v1/${path}`, {
      ...init, redirect: "error", cache: "no-store", signal: AbortSignal.timeout(15_000),
      headers: { apikey: config.key, Authorization: `Bearer ${config.key}`, ...init.headers },
    })
    if (!response.ok) throw new Error("storage_unavailable")
    return response
  } catch { throw new Error("storage_unavailable") }
}
export async function readStoredImage(key: string): Promise<Buffer> {
  if (!isImageKey(key)) throw new Error("invalid_image_key")
  const { bucket } = imageStorageConfig()
  const response = await storageRequest(`object/authenticated/${bucket}/${key}`)
  // Read with a hard bound even when a backend omits Content-Length.
  const reader = response.body!.getReader()
  const chunks: Uint8Array[] = []
  let size = 0
  try {
    for (;;) {
      const { done, value } = await reader.read()
      if (done) break
      size += value.length
      if (size > 3_000_000) throw new Error("storage_invalid_object")
      chunks.push(value)
    }
  } finally { await reader.cancel() }
  return Buffer.concat(chunks)
}
/** Only normalized, approved bytes enter the private bucket. A reference is
 * returned only after a full read-back hash check. No client filenames/URLs. */
export async function storeApprovedImage(result: ModerationResult): Promise<string> {
  if (result.decision !== "allow" || !result.approvedDataUrl?.startsWith("data:image/webp;base64,")) throw new Error("image_not_approved")
  const bytes = Buffer.from(result.approvedDataUrl.split(",")[1], "base64")
  if (!bytes.length || bytes.length > 3_000_000) throw new Error("invalid_image")
  const { bucket } = imageStorageConfig()
  // Catch a mistakenly public bucket before sending any bytes.
  const settings = await (await storageRequest(`bucket/${bucket}`)).json()
  if (settings.public !== false) throw new Error("private_image_bucket_required")
  const key = `${randomUUID()}.webp`
  await storageRequest(`object/${bucket}/${key}`, { method: "POST", headers: { "Content-Type": "image/webp", "x-upsert": "false" }, body: new Uint8Array(bytes) })
  const stored = await readStoredImage(key)
  if (createHash("sha256").update(stored).digest("hex") !== createHash("sha256").update(bytes).digest("hex")) throw new Error("storage_verification_failed")
  return `/api/media/${key}`
}

/** Bounded inventory page. Only application-generated root keys are considered. */
export async function listStoredImages(offset: number, limit = 100): Promise<{ name: string; created_at: string }[]> {
  if (!Number.isSafeInteger(offset) || offset < 0 || limit < 1 || limit > 500) throw new Error("invalid_storage_page")
  const { bucket } = imageStorageConfig()
  const response = await storageRequest(`object/list/${bucket}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prefix: "", limit, offset, sortBy: { column: "name", order: "asc" } }) })
  const rows: unknown = await response.json()
  if (!Array.isArray(rows)) throw new Error("storage_invalid_inventory")
  return rows.map(row => {
    if (!row || typeof row.name !== "string") throw new Error("storage_invalid_inventory")
    return { name: row.name, created_at: typeof row.created_at === "string" ? row.created_at : "" }
  })
}
